### ISSUE TITLE
Link to summoner settings is broken

### ISSUE THREAD

**Issue by ghallak** [kowainik/org#10]
At the end of the "Project structure" section:

> The easiest way to create a project is to use [`summoner`](https://github.com/kowainik/summoner) tool [with our own settings](https://github.com/kowainik/org/blob/master/summoner.toml).

The link to the `summoner`'s settings is broken.

**Comment by vrom911** [comment]
Thank you for pointing it out! The file `summoner.toml` was changed to `.summoner.toml`.

**Comment by vrom911** [comment]
Fixed :slightly_smiling_face:
