### ISSUE TITLE
Add minimal generic pull-request template that will work for every project

### ISSUE THREAD

**Issue by chshersh** [kowainik/org#21]
Basically: add `Resolves #{PUT_ISSUE_NUMBER_HERE}` and `Updage changelog`

**Comment by chshersh** [comment]
@vrom911 Do you think this issue should belong to the `.github` repo now? Or can we just close it since our workflow is based on `hit-on`?

**Comment by vrom911** [comment]
Closing in favour of `hit-on` workflow at the moment. Can create when we would feel the need for one :slightly_smiling_face:
