### ISSUE TITLE
Should the style guide recommend unpacking simple fields?

### ISSUE THREAD

**Issue by jkachmar** [kowainik/org#22]
GHC currently unpacks small, strict fields by default (cf. https://ghc.haskell.org/trac/ghc/ticket/7868); does this make the recommendation in [this section](https://github.com/kowainik/org/blob/master/style-guide.md#data-declaration) unnecessary?

**Comment by chshersh** [comment]
@jkachmar Thanks for bringing this up! I'm aware of such GHC features. But one of the points of this section in style guide is to inform people about such way to increase performance. However, there're alternative ways to enforce rule about unpacking fields. For example: add `{-# LANGUAGE StrictData #-}` to all files (or to `.cabal` file) and enable `-funbox-strict-fields` option. It's not clear what recommendation is better: saving some keystrokes or typing `!` and guarantee strictness or writing strict fields every time manually. Basically, _opt-in_ vs. _opt-out_. 

We use `{-# UNPACK #-}` pragmas extensively in our `typerep-map` project and it helped to increase performance a lot (the fields are arrays). So I think that the wording is good enough around unpacking:

> Additionally, unpacking simple fields often improves performance and reduces memory usage:

It doesn't say that you _must_ or even _should_ do this. But it can help.
