### ISSUE TITLE
Consider adding more warnings to the list of default warnings

### ISSUE THREAD

**Issue by chshersh** [kowainik/org#30]
Proposal for new warnings:

* Since 8.8:
    + [`-Wmissing-deriving-strategies`](https://downloads.haskell.org/ghc/8.8.1-alpha1/docs/html/users_guide/using-warnings.html#ghc-flag--Wmissing-deriving-strategies)
* Since 8.10:
    + [`-Wunused-packages`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Wunused-packages)
    + [`-Wunused-record-wildcards`](http://downloads.haskell.org/~ghc/8.10.1-rc1/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-record-wildcards)
    + [`-Wredundant-record-wildcards`](http://downloads.haskell.org/~ghc/8.10.1-rc1/docs/html/users_guide/using-warnings.html#ghc-flag--Wredundant-record-wildcards)

**Comment by chshersh** [comment]
After adding them to the style guide, we can also add them to `summoner` as well.

**Comment by vrom911** [comment]
`-Wunused-record-wildcards` and `-Wredundant-record-wildcards` is part of the `Wall` now, which we are already included 👍🏼
