### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by StevenXL** [kowainik/org#31]
Is slack still the main communication tool? If not, should the docs be updated?

**Comment by chshersh** [comment]
@StevenXL We need to update documentation, indeed. Slack is no longer the main communication tool.

**Comment by kahlil29** [comment]
I feel that if the team scales up and different people are working on different repos/tools at the same time, one single Telegram group would be problematic and would not be able to handle the separation of discussion well. 

Should we keep Slack as a backup incase this does happen? What do you guys feel?

**Comment by chshersh** [comment]
We can always return to Slack, it's not a problem :slightly_smiling_face: But currently we don't have that many people, the team is not expanding that fast and discussions are not that active at the Telegram channel So I don't expect that we will switch back to Slack in the near future.
