### ISSUE TITLE
[RFC] Create .github repo with organization-wide projects

### ISSUE THREAD

**Issue by chshersh** [kowainik/org#33]
What we can put there:

- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md
- [ ] `.github/PULL_REQUEST_TEMPLATE.md` with a line like `Resolves #ISSUE_NUMBER`

Any other ideas? We don't have `SUPPORT.md` and `SECURITY.md` files. Should we add them as well? It's also possible to add ISSUE_TEMPLATE but I'm not a fan of issue templates... I think they are project-specific and for me, it's better when I can create issues in free form.

**Comment by chshersh** [comment]
@vrom911 I guess this issue can be closed now? Since our workflow is based on `hit-on`, we don't really need PR template... What do you think?

**Comment by vrom911** [comment]
Yes, a template might be useful in some specific projects, but not in general. So, yeah, can close now :walking_woman:
